### ISSUE TITLE
Update CHANGES.md for the version 0.0.5

### ISSUE THREAD

**Issue by mrkn** [red-data-tools/unicode_plot.rb#47]

**Comment by mrkn** [comment]
Contents that must be mentioned is below:

- [x] stairs #38 by nanobowers
- [x] block canvas #39 by nanobowers
- [x] animation example #33 by mrkn and kojix2
- [x] resolve the lineplot bug of monotonic curve rendering #37 by nanobowers
- [ ] stemplot #40 by nanobowers
- [x] color option of render method #46 by mrkn, reported by kojix2
- [ ] new documentation
  - boxplot
  - lineplot
  - stemplot
  - stairs
